Hyper bump
servo/rust-websocket pull request #2
Opened 2017-03-02 13:45 UTC by avadacatavra

bump hyper to 0.10

2017-03-02 15:35 UTC, nox requested changes
Great!

2017-03-02 15:35 UTC, nox commented on Cargo.toml
> +version = "0.18.0"
Rebase, current version is already `0.18.0`.

2017-03-02 15:35 UTC, nox commented on src/client/mod.rs
> +			let sslstream = ssl.connect(connection).unwrap();
Pretty sure this should be in a `try!` expression.

2017-03-02 15:35 UTC, nox commented on src/header/accept.rs
> +		let output = hash(hash::MessageDigest::sha1(), concat_key.as_bytes()).unwrap();
Why is this fallible now?

2017-03-02 15:35 UTC, nox commented on src/server/mod.rs
> +///for connection in server {		//FIXME
What is there to fix here?

2017-03-02 15:35 UTC, nox commented on src/stream.rs
> +			WebSocketStream::Ssl(_) => panic!("Cannot clone ssl stream"),
That seems wrong.

2017-03-03 17:56 UTC, avadacatavra commented on src/stream.rs
> +			WebSocketStream::Ssl(_) => panic!("Cannot clone ssl stream"),
in SslStream the try_clone(&self) function is deprecated in newer versions and will be removed

2017-03-03 18:05 UTC, avadacatavra commented on src/header/accept.rs
> +		let output = hash(hash::MessageDigest::sha1(), concat_key.as_bytes()).unwrap();
hash now outputs a result with an ssl errorstack. hashing can fail at a number of steps where openssl calls into c. if there's an error, we're just going to want to fail.

2017-03-03 18:46 UTC, avadacatavra commented
I'm closing this in favor of my new PR #4 ...I did weird things with some configs and got all messed up.

2017-03-03 18:46 UTC, closed without merging